### ISSUE TITLE
Rice Fixes

### ISSUE THREAD

**Issue by cfis** [ankane/midas-ruby#1]
@ankane - To get the new version of Rice working, remove the *[] to lambdas. If you want a pointer the syntax you can use is +[]. See:

https://stackoverflow.com/questions/18889028/a-positive-lambda-what-sorcery-is-this

But really you need neither, just use a lambda. Note a good post about what is really happening under the covers here:

https://devblogs.microsoft.com/oldnewthing/20150220-00/?p=44623

Next, change the calls from define_method to define_function since there is no "self" object you are passing around. define_method adds an implicit self parameter to the front of the argument list while define_self does not.

Also, I would recommend not naming the extension ext - that seems to be asking for conflicts with other gems. I'd call it something like midas, so you end up with midas.so. 

Updated file attached (I did one lambda as +[] and one without...but I would do both without).

**Comment by cfis** [comment]
Hmm, github doesn't like uploading C++ files. So here it is 

```cpp
// stdlib
#include <iostream>
#include <vector>

// midas
#include <FilteringCore.hpp>
#include <NormalCore.hpp>
#include <RelationalCore.hpp>

// rice
#include <rice/rice.hpp>

void load_str(std::vector<int>& src, std::vector<int>& dst, std::vector<int>& times, const std::string& input, bool directed) {
  int* input_ptr = (int*) input.data();
  size_t n = input.size() / sizeof(int);

  if (directed) {
    for (size_t i = 0; i < n; i += 3) {
      src.push_back(input_ptr[i]);
      dst.push_back(input_ptr[i + 1]);
      times.push_back(input_ptr[i + 2]);
    }
  } else {
    for (size_t i = 0; i < n; i += 3) {
      src.push_back(input_ptr[i]);
      dst.push_back(input_ptr[i + 1]);
      times.push_back(input_ptr[i + 2]);
      src.push_back(input_ptr[i + 1]);
      dst.push_back(input_ptr[i]);
      times.push_back(input_ptr[i + 2]);
    }
  }
}

// load_data from main.cpp
// modified to throw std::runtime_error when cannot find file
// instead of exiting
void load_file(std::vector<int>& src, std::vector<int>& dst, std::vector<int>& times, const std::string& input_file, bool undirected) {
  FILE* infile = fopen(input_file.c_str(), "r");
  if (infile == NULL) {
    throw std::runtime_error("Could not read file: " + input_file);
  }

  int s, d, t;

  if (undirected == false) {
    while (fscanf(infile, "%d,%d,%d", &s, &d, &t) == 3) {
      src.push_back(s);
      dst.push_back(d);
      times.push_back(t);
    }
  } else {
    while (fscanf(infile, "%d,%d,%d", &s, &d, &t) == 3) {
      src.push_back(s);
      dst.push_back(d);
      times.push_back(t);
      src.push_back(d);
      dst.push_back(s);
      times.push_back(t);
    }
  }
}

std::string fit_predict(std::vector<int>& src, std::vector<int>& dst, std::vector<int>& times, int num_rows, int num_buckets, float factor, float threshold, bool relations, int seed) {
  srand(seed);
  size_t n = src.size();
  const auto result = new float[n];

  if (!std::isnan(threshold)) {
    MIDAS::FilteringCore midas(num_rows, num_buckets, threshold, factor);
    for (size_t i = 0; i < n; i++) {
      result[i] = midas(src[i], dst[i], times[i]);
    }
  } else if (relations) {
    MIDAS::RelationalCore midas(num_rows, num_buckets, factor);
    for (size_t i = 0; i < n; i++) {
      result[i] = midas(src[i], dst[i], times[i]);
    }
  } else {
    MIDAS::NormalCore midas(num_rows, num_buckets);
    for (size_t i = 0; i < n; i++) {
      result[i] = midas(src[i], dst[i], times[i]);
    }
  }
  return std::string((char*) result, sizeof(float) / sizeof(char) * n);
}

extern "C"
void Init_ext() {
  auto rb_mMidas = Rice::define_module("Midas");

  Rice::define_class_under(rb_mMidas, "Detector")
    .define_function(
      "_fit_predict_str",
      +[](const std::string& input, int num_rows, int num_buckets, float factor, float threshold, bool relations, bool directed, int seed) {
        std::vector<int> src, dst, times;
        load_str(src, dst, times, input, directed);
        return fit_predict(src, dst, times, num_rows, num_buckets, factor, threshold, relations, seed);
      })
    .define_function(
      "_fit_predict_file",
      [](const std::string& input, int num_rows, int num_buckets, float factor, float threshold, bool relations, bool directed, int seed) {
        std::vector<int> src, dst, times;
        load_file(src, dst, times, input, !directed);
        return fit_predict(src, dst, times, num_rows, num_buckets, factor, threshold, relations, seed);
      });
}
```

**Comment by ankane** [comment]
Thanks @cfis, that fixed the error on Mac: https://github.com/ankane/midas/compare/rice-header-only2. Also, thanks for sharing the lambda resources!

I'm not sure if there's a way to make it work with the new changes/what the trade-offs are, but I think having a single C++ function for both situations (with and without self) as the current version does is simpler for users than having two different ones (cc @jasonroelofs). *Edit: This suggestion is very minor compared to the awesome improvements the new version brings, so may not even be worth discussing.*

Re ext: I have noticed the Ruby convention is to name it `midas` instead of `ext`, so may do that after the header-only stuff. I haven't seen any conflicts when using gems together that use `ext`, like Midas and Faiss, so not sure what's going on there.

**Comment by cfis** [comment]
The problem with the single function is that it doesn't allow the use of lambdas for both define_method and define_global_function. I thought it was better to have global support for lambdas (so define_method, define_singleton_method, define_global_function) then it was to have a single method. It also makes Rice simpler - the dual support led to various special cases in Rice to make it work.

Thus I changed it. I do think this is better in some ways, it makes it explicit whether you want a self parameter or not. In the same way you could have just define_method and not define_singleton_method, but the library has both to make it more explicit what you are trying to do.

The issue I was wondering with ext.so is they both have Init_ext as the initialization function. But thinking about it more, that function would only be triggered in the dll/so being loaded. So I take back my comment, there wouldn't be conflicts.

**Comment by cfis** [comment]
On the lambdas, I think msvc and gcc are acting differently. 

+[] works on msvc, didn't test gcc
*[] does not work on msvc, does work on gcc. MSVC fails because it gets confused between different call types (fastvector and cdecl) - explained a bit in that blog post I linked

**Comment by ankane** [comment]
Thanks for the explanation/context on the change.

I updated Faiss ([diff](https://github.com/ankane/faiss/compare/rice-header-only) - [CI](https://github.com/ankane/faiss/runs/2017677446?check_suite_focus=true)), which eliminated the "wrong number of arguments" errors.

**Comment by cfis** [comment]
Cool. Somehow inheritance is broken when I test that library, have to check why.

**Comment by ankane** [comment]
Great, I started a new issue to track progress of testing libraries and migration notes: https://github.com/ankane/midas/issues/2
